/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author pc-click
 */
public class FicheClient extends javax.swing.JFrame {

    /**
     * Creates new form FicheClient
     */
    public FicheClient() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        lieu = new javax.swing.JTextField();
        datee = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        nationalite = new javax.swing.JTextField();
        numcarte = new javax.swing.JTextField();
        profession = new javax.swing.JTextField();
        typepaiement = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        confirmer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 5, 8));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 236, 228));
        jLabel1.setText("Fiche Client");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 14, 147, 32);

        jButton1.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc-click\\Documents\\NetBeansProjects\\HotelLaGazellee\\Documents\\NetBeansProjects\\JavaApplication7\\src\\HotelPackage\\exitpng.png")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1325, 14, 24, 25);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 60));

        jPanel2.setBackground(new java.awt.Color(244, 240, 235));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(250, 249, 248));
        jPanel4.setPreferredSize(new java.awt.Dimension(569, 52));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 5, 8));
        jLabel3.setText("Informations générales");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(20, 0, 204, 50);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(72, 20, 600, 47);

        jPanel6.setBackground(new java.awt.Color(250, 249, 248));

        jPanel11.setBackground(new java.awt.Color(244, 240, 235));

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 5, 8));
        jLabel6.setText("Lieu de naissance");

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 5, 8));
        jLabel7.setText("Date de naissance");

        jLabel12.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(2, 5, 8));
        jLabel12.setText("Prénom");

        jLabel13.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(2, 5, 8));
        jLabel13.setText("Nom");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        nom.setBackground(new java.awt.Color(250, 249, 248));
        nom.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        nom.setForeground(new java.awt.Color(2, 5, 8));
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomKeyTyped(evt);
            }
        });

        prenom.setBackground(new java.awt.Color(250, 249, 248));
        prenom.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        prenom.setForeground(new java.awt.Color(2, 5, 8));
        prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prenomKeyTyped(evt);
            }
        });

        lieu.setBackground(new java.awt.Color(250, 249, 248));
        lieu.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        lieu.setForeground(new java.awt.Color(2, 5, 8));

        datee.setBackground(new java.awt.Color(250, 249, 248));
        datee.setForeground(new java.awt.Color(2, 5, 8));
        datee.setDateFormatString("yyyy-MM-dd");
        datee.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(prenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(lieu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom)
                    .addComponent(datee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lieu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(72, 72, 601, 225);

        jPanel7.setBackground(new java.awt.Color(250, 249, 248));

        email.setBackground(new java.awt.Color(250, 249, 248));
        email.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        email.setForeground(new java.awt.Color(2, 5, 8));

        telephone.setBackground(new java.awt.Color(250, 249, 248));
        telephone.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        telephone.setForeground(new java.awt.Color(2, 5, 8));
        telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telephoneKeyTyped(evt);
            }
        });

        jPanel19.setBackground(new java.awt.Color(244, 240, 235));

        jLabel40.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(2, 5, 8));
        jLabel40.setText("Email");

        jLabel41.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(2, 5, 8));
        jLabel41.setText("Téléphone");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(telephone))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7);
        jPanel7.setBounds(685, 72, 596, 225);

        jPanel8.setBackground(new java.awt.Color(250, 249, 248));
        jPanel8.setPreferredSize(new java.awt.Dimension(744, 35));
        jPanel8.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 5, 8));
        jLabel4.setText("Informations suplémentaires");
        jPanel8.add(jLabel4);
        jLabel4.setBounds(28, 12, 253, 23);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(72, 309, 601, 45);

        jPanel9.setBackground(new java.awt.Color(250, 249, 248));

        jPanel20.setBackground(new java.awt.Color(244, 240, 235));

        jLabel42.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(2, 5, 8));
        jLabel42.setText("Profession");

        jLabel43.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(2, 5, 8));
        jLabel43.setText("Type de paiement");

        jLabel44.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(2, 5, 8));
        jLabel44.setText("N° carte Nationale");

        jLabel45.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(2, 5, 8));
        jLabel45.setText("Nationalité");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        nationalite.setBackground(new java.awt.Color(250, 249, 248));
        nationalite.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        nationalite.setForeground(new java.awt.Color(2, 5, 8));
        nationalite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nationaliteKeyTyped(evt);
            }
        });

        numcarte.setBackground(new java.awt.Color(250, 249, 248));
        numcarte.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        numcarte.setForeground(new java.awt.Color(2, 5, 8));
        numcarte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numcarteKeyTyped(evt);
            }
        });

        profession.setBackground(new java.awt.Color(250, 249, 248));
        profession.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        profession.setForeground(new java.awt.Color(2, 5, 8));
        profession.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                professionKeyTyped(evt);
            }
        });

        typepaiement.setBackground(new java.awt.Color(250, 249, 248));
        typepaiement.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        typepaiement.setForeground(new java.awt.Color(2, 5, 8));
        typepaiement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chéque", "Provisoirement", "Prélévement", "Virement" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(profession, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numcarte, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nationalite, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(typepaiement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(nationalite, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numcarte, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typepaiement, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profession, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9);
        jPanel9.setBounds(72, 360, 601, 252);

        jPanel10.setBackground(new java.awt.Color(250, 249, 248));
        jPanel10.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(2, 5, 8));
        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 5, 8));
        jLabel5.setText("Solde:");
        jPanel10.add(jLabel5);
        jLabel5.setBounds(73, 120, 68, 29);

        jPanel2.add(jPanel10);
        jPanel10.setBounds(685, 309, 0, 309);

        confirmer.setBackground(new java.awt.Color(0, 0, 0));
        confirmer.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        confirmer.setForeground(new java.awt.Color(250, 249, 248));
        confirmer.setText("Confirmer");
        confirmer.setPreferredSize(new java.awt.Dimension(150, 52));
        confirmer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmerFocusLost(evt);
            }
        });
        confirmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmerMousePressed(evt);
            }
        });
        confirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerActionPerformed(evt);
            }
        });
        jPanel2.add(confirmer);
        confirmer.setBounds(1000, 550, 133, 43);

        annuler.setBackground(new java.awt.Color(0, 0, 0));
        annuler.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        annuler.setForeground(new java.awt.Color(250, 249, 248));
        annuler.setText("Annuler");
        annuler.setPreferredSize(new java.awt.Dimension(150, 52));
        annuler.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                annulerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                annulerFocusLost(evt);
            }
        });
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        jPanel2.add(annuler);
        annuler.setBounds(1140, 550, 120, 43);

        jPanel5.setBackground(new java.awt.Color(250, 249, 248));
        jPanel5.setPreferredSize(new java.awt.Dimension(569, 52));
        jPanel5.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 5, 8));
        jLabel8.setText("Coordonnées");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(15, 12, 115, 23);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(685, 19, 596, 47);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1460, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed

        

    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new Client().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmerFocusGained
        confirmer.setBackground(new java.awt.Color(250,249,248));
        confirmer.setForeground(new java.awt.Color(2, 5, 8));

    }//GEN-LAST:event_confirmerFocusGained

    private void confirmerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmerFocusLost
        confirmer.setBackground(new java.awt.Color(0,0,0));
        confirmer.setForeground(new java.awt.Color(250,249,248));

    }//GEN-LAST:event_confirmerFocusLost

    private void confirmerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmerMouseClicked
        new Client().setVisible(true);
        //this.setVisible(false);
        //this.dispose();

    }//GEN-LAST:event_confirmerMouseClicked

    private void confirmerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmerMousePressed

    }//GEN-LAST:event_confirmerMousePressed

    private void confirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerActionPerformed
        if((nom.getText().isEmpty())|(prenom.getText().isEmpty())|(lieu.getText().isEmpty())|(nationalite.getText().isEmpty())|(numcarte.getText().isEmpty())|(telephone.getText().isEmpty())|(email.getText().isEmpty())|(profession.getText().isEmpty())){    
        JOptionPane.showMessageDialog(this, "Tous les champs doivent etre remplis !!","Erreur",JOptionPane.ERROR_MESSAGE);
      }
      else{
        DateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String DateString=sdf.format(datee.getDate());
       
         //JOptionPane.showMessageDialog(null, DateString);
        try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            
            //requete
            /*String SQL ="insert into clientt(Nom,Prenom,Date_nai,Lieu_nai,Nationalite,numcarteN,TypePaiment,Profession,Telephone,Email)"+
              "values("+"\""+nom.getText().toString()+"\""+","+"\""+prenom.getText().toString()+"\""+",'"+DateString+"',"+"\""+lieu.getText().toString()+"\"" +","+"\""+nationalite.getText().toString()+"\""+","+"\""+numcarte.getText().toString()+"\""+","+"\""+typepaiement.getSelectedItem().toString()+"\""+","+"\""+profession.getText().toString()+"\""+","+"\""+telephone.getText().toString()+"\""+","+"\""+email.getText().toString()+"\""+");"; */
            String SQL ="insert into clientt(Nom,Prenom,Date_nai,Lieu_nai,Nationalite,numcarteN,TypePaiment,Profession,Telephone,Email)"+
              "values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement st =cnx.prepareStatement(SQL);
            st.setString(1,nom.getText().toString() );
            st.setString(2,prenom.getText().toString() );
            st.setString(3,DateString );
            st.setString(4,lieu.getText().toString() );
            st.setString(5,nationalite.getText().toString() );
            st.setString(6,numcarte.getText().toString() );
            st.setString(7,typepaiement.getSelectedItem().toString() );
            st.setString(8,profession.getText().toString() );
            st.setString(9,telephone.getText().toString() );
            st.setString(10,email.getText().toString() );
            st.executeUpdate(); 
            JOptionPane.showMessageDialog(this," Oprération réussie ","Info",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new Client().setVisible(true);
           
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}}
    }//GEN-LAST:event_confirmerActionPerformed

    private void annulerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_annulerFocusGained
        annuler.setBackground(new java.awt.Color(250,249,248));
        annuler.setForeground(new java.awt.Color(2, 5, 8));
    }//GEN-LAST:event_annulerFocusGained

    private void annulerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_annulerFocusLost
        annuler.setBackground(new java.awt.Color(0,0,0));
        annuler.setForeground(new java.awt.Color(250,249,248));
    }//GEN-LAST:event_annulerFocusLost

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
       new Client().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_annulerActionPerformed

    private void nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyTyped
       char text= evt.getKeyChar();
       if(!(Character.isAlphabetic(text))){
       evt.consume();}
    }//GEN-LAST:event_nomKeyTyped

    private void prenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomKeyTyped
         char text= evt.getKeyChar();
       if(!(Character.isAlphabetic(text))){
       evt.consume();}
    }//GEN-LAST:event_prenomKeyTyped

    private void telephoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneKeyTyped
        char text= evt.getKeyChar();
       if(!(Character.isDigit(text))){
       evt.consume();}
    }//GEN-LAST:event_telephoneKeyTyped

    private void numcarteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numcarteKeyTyped
         char text= evt.getKeyChar();
       if(!(Character.isDigit(text))){
       evt.consume();}
    }//GEN-LAST:event_numcarteKeyTyped

    private void nationaliteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationaliteKeyTyped
         char text= evt.getKeyChar();
       if(!(Character.isAlphabetic(text))){
       evt.consume();}
    }//GEN-LAST:event_nationaliteKeyTyped

    private void professionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_professionKeyTyped
       char text= evt.getKeyChar();
       if(!(Character.isAlphabetic(text))){
       evt.consume();}
    }//GEN-LAST:event_professionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FicheClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JButton confirmer;
    private com.toedter.calendar.JDateChooser datee;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lieu;
    private javax.swing.JTextField nationalite;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField numcarte;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField profession;
    private javax.swing.JTextField telephone;
    private javax.swing.JComboBox<String> typepaiement;
    // End of variables declaration//GEN-END:variables
}
