/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pc-click
 */
public class FicheSalle extends javax.swing.JFrame {

    /**
     * Creates new form FicheSalle
     */
    public FicheSalle() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        NumSalle = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        prix = new javax.swing.JTextField();
        BConfirmer = new javax.swing.JButton();
        BAnnuler = new javax.swing.JButton();
        Categorie = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 5, 8));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 236, 228));
        jLabel1.setText("Fiche Salle");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(21, 14, 130, 32);

        jButton1.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc-click\\Documents\\NetBeansProjects\\HotelLaGazellee\\Documents\\NetBeansProjects\\JavaApplication7\\src\\HotelPackage\\exitpng.png")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1325, 14, 24, 25);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 60));

        jPanel2.setBackground(new java.awt.Color(250, 249, 248));
        jPanel2.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(2, 5, 8));
        jLabel17.setText("N° de salle");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(98, 91, 97, 25);

        NumSalle.setBackground(new java.awt.Color(250, 249, 248));
        NumSalle.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        NumSalle.setForeground(new java.awt.Color(2, 5, 8));
        NumSalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumSalleKeyTyped(evt);
            }
        });
        jPanel2.add(NumSalle);
        NumSalle.setBounds(250, 80, 270, 38);

        jLabel20.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(2, 5, 8));
        jLabel20.setText("Catégorie");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(684, 91, 88, 25);

        jLabel22.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(2, 5, 8));
        jLabel22.setText("Prix de salle");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(98, 167, 113, 25);

        prix.setBackground(new java.awt.Color(250, 249, 248));
        prix.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        prix.setForeground(new java.awt.Color(2, 5, 8));
        prix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prixKeyTyped(evt);
            }
        });
        jPanel2.add(prix);
        prix.setBounds(250, 160, 270, 38);

        BConfirmer.setBackground(new java.awt.Color(0, 0, 0));
        BConfirmer.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        BConfirmer.setForeground(new java.awt.Color(250, 249, 248));
        BConfirmer.setText("Confirmer");
        BConfirmer.setPreferredSize(new java.awt.Dimension(150, 52));
        BConfirmer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BConfirmerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BConfirmerFocusLost(evt);
            }
        });
        BConfirmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BConfirmerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BConfirmerMousePressed(evt);
            }
        });
        BConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConfirmerActionPerformed(evt);
            }
        });
        jPanel2.add(BConfirmer);
        BConfirmer.setBounds(1025, 612, 133, 43);

        BAnnuler.setBackground(new java.awt.Color(0, 0, 0));
        BAnnuler.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        BAnnuler.setForeground(new java.awt.Color(250, 249, 248));
        BAnnuler.setText("Annuler");
        BAnnuler.setPreferredSize(new java.awt.Dimension(150, 52));
        BAnnuler.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BAnnulerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BAnnulerFocusLost(evt);
            }
        });
        BAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BAnnulerMousePressed(evt);
            }
        });
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });
        jPanel2.add(BAnnuler);
        BAnnuler.setBounds(1163, 612, 120, 43);

        Categorie.setBackground(new java.awt.Color(250, 249, 248));
        Categorie.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        Categorie.setForeground(new java.awt.Color(2, 5, 8));
        Categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salle de formation", "Salle d audition", "Salle de conference", "Salle de reunion", "Salle de seminaire", " ", " " }));
        jPanel2.add(Categorie);
        Categorie.setBounds(790, 70, 270, 40);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1460, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        new Salle().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BAnnulerActionPerformed

    private void BAnnulerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BAnnulerFocusLost
        BAnnuler.setBackground(new java.awt.Color(0,0,0));
        BAnnuler.setForeground(new java.awt.Color(250,249,248));
    }//GEN-LAST:event_BAnnulerFocusLost

    private void BAnnulerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BAnnulerFocusGained
        BAnnuler.setBackground(new java.awt.Color(250,249,248));
        BAnnuler.setForeground(new java.awt.Color(2, 5, 8));
    }//GEN-LAST:event_BAnnulerFocusGained

    private void BConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConfirmerActionPerformed
      ArrayList<String> table= new ArrayList<>();
      // conditions sur les champs 
      if((NumSalle.getText().isEmpty())|(prix.getText().isEmpty())){
      JOptionPane.showMessageDialog(this, "Tous les champs doivent etre remplis !!","Erreur",JOptionPane.ERROR_MESSAGE);
      }
      else{ 
         try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL="select NumSalle from salle ;";
            ResultSet rs= st.executeQuery(SQL);
            while(rs.next()){
                //add data until finish
              table.add(rs.getString("NumSalle"));
            }
            cnx.close();
           
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
         for(int i=0;i<table.size();i++){
             String num =NumSalle.getText().toString();
             String num2=table.get(i);
            if(!((num).equals(num2))){
             //remplir BD 
             try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL ="insert into salle(NumSalle,PrixSalle,CategorieSalle,DisponibilteSalle)"+
              "values("+NumSalle.getText().toString()+","+prix.getText().toString()+","+"\""+Categorie.getSelectedItem().toString()+"\"" +","+"\""+1+"\""+");";
            
            st.executeUpdate(SQL); 
            JOptionPane.showMessageDialog(this," Insérer avec succès ","Info",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new Salle().setVisible(true);
           
        }catch(Exception e){
        /*JOptionPane.showMessageDialog(null,e);*/}
             
            }
            else{JOptionPane.showMessageDialog(this,"le numéro de salle existe déja !!","Erreur",JOptionPane.ERROR_MESSAGE);}}}
    }//GEN-LAST:event_BConfirmerActionPerformed

    private void BConfirmerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BConfirmerMousePressed
   
    }//GEN-LAST:event_BConfirmerMousePressed

    private void BConfirmerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BConfirmerMouseClicked
        
    }//GEN-LAST:event_BConfirmerMouseClicked

    private void BConfirmerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BConfirmerFocusLost
        BConfirmer.setBackground(new java.awt.Color(0,0,0));
        BConfirmer.setForeground(new java.awt.Color(250,249,248));
    }//GEN-LAST:event_BConfirmerFocusLost

    private void BConfirmerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BConfirmerFocusGained
        BConfirmer.setBackground(new java.awt.Color(250,249,248));
        BConfirmer.setForeground(new java.awt.Color(2, 5, 8));
    }//GEN-LAST:event_BConfirmerFocusGained

    private void BAnnulerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BAnnulerMousePressed
        new Salle().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BAnnulerMousePressed

    private void NumSalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumSalleKeyTyped
         char text= evt.getKeyChar();
       if(!(Character.isDigit(text))){
       evt.consume();}
    }//GEN-LAST:event_NumSalleKeyTyped

    private void prixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyTyped
        char text= evt.getKeyChar();
       if(!(Character.isDigit(text))){
       evt.consume();}
    }//GEN-LAST:event_prixKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FicheSalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BConfirmer;
    private javax.swing.JComboBox<String> Categorie;
    private javax.swing.JTextField NumSalle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField prix;
    // End of variables declaration//GEN-END:variables
}
