/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelPackage;


import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc-click
 */
public class FicheChambres extends javax.swing.JFrame {
Connection cnx=null;
    /**
     * Creates new form FicheChambres
     */
    public FicheChambres() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        NumChambre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        NumBloc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        NumEtage = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Categorie = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        NbrLits = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Prix = new javax.swing.JTextField();
        Confirme = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 5, 8));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 236, 228));
        jLabel1.setText("Fiche Chambre");

        jButton1.setBackground(new java.awt.Color(2, 5, 8,0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc-click\\Documents\\NetBeansProjects\\HotelLaGazellee\\Documents\\NetBeansProjects\\JavaApplication7\\src\\HotelPackage\\exitpng.png")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1122, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 60));

        jPanel2.setBackground(new java.awt.Color(250, 249, 248));

        jLabel17.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(2, 5, 8));
        jLabel17.setText("N° de chambre");

        NumChambre.setBackground(new java.awt.Color(250, 249, 248));
        NumChambre.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        NumChambre.setForeground(new java.awt.Color(2, 5, 8));

        jLabel18.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(2, 5, 8));
        jLabel18.setText("N° de bloc");

        NumBloc.setBackground(new java.awt.Color(250, 249, 248));
        NumBloc.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        NumBloc.setForeground(new java.awt.Color(2, 5, 8));

        jLabel19.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(2, 5, 8));
        jLabel19.setText("N° de étage");

        NumEtage.setBackground(new java.awt.Color(250, 249, 248));
        NumEtage.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        NumEtage.setForeground(new java.awt.Color(2, 5, 8));

        jLabel20.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(2, 5, 8));
        jLabel20.setText("Catégorie");

        Categorie.setBackground(new java.awt.Color(250, 249, 248));
        Categorie.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        Categorie.setForeground(new java.awt.Color(2, 5, 8));

        jLabel21.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(2, 5, 8));
        jLabel21.setText("Nbr de lits");

        NbrLits.setBackground(new java.awt.Color(250, 249, 248));
        NbrLits.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        NbrLits.setForeground(new java.awt.Color(2, 5, 8));

        jLabel22.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(2, 5, 8));
        jLabel22.setText("Prix de chambre");

        Prix.setBackground(new java.awt.Color(250, 249, 248));
        Prix.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        Prix.setForeground(new java.awt.Color(2, 5, 8));

        Confirme.setBackground(new java.awt.Color(0, 0, 0));
        Confirme.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        Confirme.setForeground(new java.awt.Color(250, 249, 248));
        Confirme.setText("Confirmer");
        Confirme.setPreferredSize(new java.awt.Dimension(150, 52));
        Confirme.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ConfirmeMouseMoved(evt);
            }
        });
        Confirme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfirmeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmeFocusLost(evt);
            }
        });
        Confirme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConfirmeMousePressed(evt);
            }
        });
        Confirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmeActionPerformed(evt);
            }
        });

        Annuler.setBackground(new java.awt.Color(0, 0, 0));
        Annuler.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        Annuler.setForeground(new java.awt.Color(250, 249, 248));
        Annuler.setText("Annuler");
        Annuler.setPreferredSize(new java.awt.Dimension(150, 52));
        Annuler.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AnnulerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AnnulerFocusLost(evt);
            }
        });
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NumEtage, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumChambre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumBloc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(113, 113, 113)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(Prix, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Categorie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NbrLits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(261, 261, 261))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirme, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(Categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(NbrLits, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(Prix, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(NumChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(NumBloc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(NumEtage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirme, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(305, 305, 305))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1460, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed

    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Chambre().setVisible(true);
        this.dispose();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ConfirmeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmeFocusGained
        Confirme.setBackground(new java.awt.Color(250,249,248));
        Confirme.setForeground(new java.awt.Color(2, 5, 8));
    }//GEN-LAST:event_ConfirmeFocusGained

    private void ConfirmeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmeFocusLost
        Confirme.setBackground(new java.awt.Color(0,0,0));
        Confirme.setForeground(new java.awt.Color(250,249,248));
    }//GEN-LAST:event_ConfirmeFocusLost

    private void ConfirmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmeMouseClicked
      
    }//GEN-LAST:event_ConfirmeMouseClicked

    private void ConfirmeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmeMousePressed

    }//GEN-LAST:event_ConfirmeMousePressed

    private void ConfirmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmeActionPerformed
      // conditions sur les champs 
      int k=0;
      String catégorie= Categorie.getText().toString(); 
      try{
        Integer.parseInt(NumChambre.getText());
        k++;
    }catch(Exception e){JOptionPane.showMessageDialog(null, "la N° de chambre doit etre un nombre entier !!");;} 
        try{
        Integer.parseInt(NumBloc.getText());
        k++;
    }catch(Exception e){JOptionPane.showMessageDialog(null, "la N° de bloc doit etre un nombre entier !!");} 
       try{
        Integer.parseInt(NumEtage.getText());
        k++;
    }catch(Exception e){JOptionPane.showMessageDialog(null, "la N° de l'étage doit etre un nombre entier !!");}  
       try{
        Integer.parseInt(NbrLits.getText());
        k++;
    }catch(Exception e){JOptionPane.showMessageDialog(null, "le nombre de lits doit etre un nombre entier !!");} 
      try{
        Double.parseDouble(Prix.getText());
        k++;
    }catch(Exception e){JOptionPane.showMessageDialog(null, "le prix de chambre doit etre un nombre !!");}  
         
      //remplir BD 
      if(k==5){
      try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL ="insert into chambre(NumChambre,NumBloc,NumEtage,Categorie,NbrLits,PrixChambre,Disponible)"+
              "values("+NumChambre.getText().toString()+","+NumBloc.getText().toString()+","+NumEtage.getText().toString()+","+"\""+Categorie.getText().toString()+"\"" +","+NbrLits.getText().toString()+","+Prix.getText().toString()+","+1+");";
            
            st.executeUpdate(SQL); 
            JOptionPane.showMessageDialog(null, "Oprération réussie");
            this.dispose();
            new Chambre().setVisible(true);
           
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}}
      
      
        
    }//GEN-LAST:event_ConfirmeActionPerformed

    private void AnnulerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AnnulerFocusGained
        Annuler.setBackground(new java.awt.Color(250,249,248));
        Annuler.setForeground(new java.awt.Color(2, 5, 8));
    }//GEN-LAST:event_AnnulerFocusGained

    private void AnnulerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AnnulerFocusLost
        Annuler.setBackground(new java.awt.Color(0,0,0));
        Annuler.setForeground(new java.awt.Color(250,249,248));
    }//GEN-LAST:event_AnnulerFocusLost

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        new Chambre().setVisible(true);
        this.dispose();
      
           
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ConfirmeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmeMouseMoved
        
    }//GEN-LAST:event_ConfirmeMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheChambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheChambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheChambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheChambres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FicheChambres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField Categorie;
    private javax.swing.JButton Confirme;
    private javax.swing.JTextField NbrLits;
    private javax.swing.JTextField NumBloc;
    private javax.swing.JTextField NumChambre;
    private javax.swing.JTextField NumEtage;
    private javax.swing.JTextField Prix;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
