/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc-click
 */
public class Modifierchambre extends javax.swing.JFrame {
  String selectvalue;
    /**
     * Creates new form Modifierchambre
     */
    public Modifierchambre() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
        updatecombox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BModifier = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        NumChambre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        NumBloc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        NumEtage = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Categorie1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        NbrLits = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Prix = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 5, 8));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 236, 228));
        jLabel1.setText("Chambre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(21, 14, 109, 32);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Crash.AMOULA-PC\\Desktop\\HotelLaGazelle\\Documents\\NetBeansProjects\\JavaApplication7\\src\\HotelPackage\\exitpng.png")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1325, 14, 24, 25);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 60));

        jPanel2.setBackground(new java.awt.Color(250, 249, 248));
        jPanel2.setLayout(null);

        BModifier.setBackground(new java.awt.Color(0, 0, 0));
        BModifier.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        BModifier.setForeground(new java.awt.Color(250, 249, 248));
        BModifier.setText(" Modifier");
        BModifier.setPreferredSize(new java.awt.Dimension(150, 52));
        BModifier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BModifierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BModifierFocusLost(evt);
            }
        });
        BModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BModifierMousePressed(evt);
            }
        });
        BModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModifierActionPerformed(evt);
            }
        });
        jPanel2.add(BModifier);
        BModifier.setBounds(1137, 521, 158, 43);

        jLabel20.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(2, 5, 8));
        jLabel20.setText("Num chambre ");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(79, 81, 133, 25);

        jLabel17.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(2, 5, 8));
        jLabel17.setText("N° de chambre");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(163, 207, 134, 25);

        NumChambre.setBackground(new java.awt.Color(250, 249, 248));
        NumChambre.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        NumChambre.setForeground(new java.awt.Color(2, 5, 8));
        jPanel2.add(NumChambre);
        NumChambre.setBounds(339, 202, 270, 38);

        jLabel18.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(2, 5, 8));
        jLabel18.setText("N° de bloc");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(163, 270, 94, 25);

        NumBloc.setBackground(new java.awt.Color(250, 249, 248));
        NumBloc.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        NumBloc.setForeground(new java.awt.Color(2, 5, 8));
        jPanel2.add(NumBloc);
        NumBloc.setBounds(339, 265, 270, 38);

        jLabel19.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(2, 5, 8));
        jLabel19.setText("N° de étage");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(163, 336, 105, 25);

        NumEtage.setBackground(new java.awt.Color(250, 249, 248));
        NumEtage.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        NumEtage.setForeground(new java.awt.Color(2, 5, 8));
        jPanel2.add(NumEtage);
        NumEtage.setBounds(339, 331, 270, 38);

        jLabel21.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(2, 5, 8));
        jLabel21.setText("Catégorie");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(748, 207, 88, 25);

        Categorie1.setBackground(new java.awt.Color(250, 249, 248));
        Categorie1.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        Categorie1.setForeground(new java.awt.Color(2, 5, 8));
        jPanel2.add(Categorie1);
        Categorie1.setBounds(918, 202, 270, 38);

        jLabel22.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(2, 5, 8));
        jLabel22.setText("Nbr de lits");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(748, 270, 97, 25);

        NbrLits.setBackground(new java.awt.Color(250, 249, 248));
        NbrLits.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        NbrLits.setForeground(new java.awt.Color(2, 5, 8));
        jPanel2.add(NbrLits);
        NbrLits.setBounds(918, 265, 270, 38);

        jLabel23.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(2, 5, 8));
        jLabel23.setText("Prix de chambre");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(748, 336, 150, 25);

        Prix.setBackground(new java.awt.Color(250, 249, 248));
        Prix.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        Prix.setForeground(new java.awt.Color(2, 5, 8));
        jPanel2.add(Prix);
        Prix.setBounds(916, 331, 270, 38);

        jComboBox1.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(2, 5, 8));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(247, 76, 258, 36);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1460, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
     new Chambre().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BModifierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BModifierFocusGained
        BModifier.setBackground(new java.awt.Color(250,249,248));
        BModifier.setForeground(new java.awt.Color(2, 5, 8));
    }//GEN-LAST:event_BModifierFocusGained

    private void BModifierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BModifierFocusLost
        BModifier.setBackground(new java.awt.Color(0,0,0));
        BModifier.setForeground(new java.awt.Color(250,249,248));
    }//GEN-LAST:event_BModifierFocusLost

    private void BModifierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BModifierMousePressed
        
    }//GEN-LAST:event_BModifierMousePressed

    private void BModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModifierActionPerformed
      // conditions sur les champs 
      int k=0;
      String catégorie= Categorie1.getText().toString(); 
      try{
        Integer.parseInt(NumChambre.getText());
        k++;
    }catch(Exception e){JOptionPane.showMessageDialog(null, "la N° de chambre doit etre un nombre entier !!");;} 
        try{
        Integer.parseInt(NumBloc.getText());
        k++;
    }catch(Exception e){JOptionPane.showMessageDialog(null, "la N° de bloc doit etre un nombre entier !!");} 
       try{
        Integer.parseInt(NumEtage.getText());
        k++;
    }catch(Exception e){JOptionPane.showMessageDialog(null, "la N° de l'étage doit etre un nombre entier !!");}  
       try{
        Integer.parseInt(NbrLits.getText());
        k++;
    }catch(Exception e){JOptionPane.showMessageDialog(null, "le nombre de lits doit etre un nombre entier !!");} 
      try{
        Double.parseDouble(Prix.getText());
        k++;
    }catch(Exception e){JOptionPane.showMessageDialog(null, "le prix de chambre doit etre un nombre !!");}  
         
      //remplir BD 
      selectvalue=jComboBox1.getSelectedItem().toString();
      if(k==5){
      try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL ="update chambre  set NumChambre='"+NumChambre.getText().toString()+"',NumBloc ='"+NumBloc.getText().toString()+"',NumEtage ='"+NumEtage.getText().toString()+"',Categorie ='"+Categorie1.getText().toString()+"', NbrLits ='"+NbrLits.getText().toString()+"',PrixChambre ='"+Prix.getText().toString()+"' where NumChambre='"+selectvalue+"';";
            
            st.executeUpdate(SQL); 
            JOptionPane.showMessageDialog(null, "Oprération réussie");
            
            new Chambre().setVisible(true);
            this.dispose();
           
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}}
    }//GEN-LAST:event_BModifierActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       selectvalue= jComboBox1.getSelectedItem().toString();
      try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL="select * from chambre where NumChambre="+selectvalue+";";
            ResultSet rs= st.executeQuery(SQL);
            while(rs.next()){
                //add data until finish
                String Numbloc=String.valueOf(rs.getInt("NumBloc"));
                String Numetage=String.valueOf(rs.getInt("NumEtage"));
                String catégorie=String.valueOf(rs.getString("Categorie"));
                String Nbrlits=String.valueOf(rs.getInt("NbrLits"));
                String prix=String.valueOf(rs.getDouble("PrixChambre"));
                NumChambre.setText(selectvalue);
                NumBloc.setText(Numbloc);
                NumEtage.setText(Numetage);
                Categorie1.setText(catégorie);
                NbrLits.setText(Nbrlits);
                Prix.setText(prix);
                
            }
            cnx.close();
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jComboBox1ActionPerformed
    public void updatecombox(){
    
    try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL="select NumChambre from chambre;";
            ResultSet rs= st.executeQuery(SQL);
            while(rs.next()){
                //add data until finish
              jComboBox1.addItem(rs.getString("NumChambre"));
            }
            cnx.close();
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifierchambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifierchambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifierchambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifierchambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifierchambre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModifier;
    private javax.swing.JTextField Categorie1;
    private javax.swing.JTextField NbrLits;
    private javax.swing.JTextField NumBloc;
    private javax.swing.JTextField NumChambre;
    private javax.swing.JTextField NumEtage;
    private javax.swing.JTextField Prix;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
