/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelPackage;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc-click
 */
public class PrintFacture extends javax.swing.JFrame {
 double prixchambre,prixsalle;
 double prixtotalechambre=0.0;
 double prixtotalesalle=0.0;
 double prixproduit;
 double prixproduittotal=0.0;
 double prixpappel=0.0;
 double prixappeltotal=0.0;
 double prixtotal=0.0;
 
    /**
     * Creates new form PrintFacture
     */
    public PrintFacture() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
        
        updateIDFacture();
        Text.append("\t************************************************************\t\n\n");
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Nom = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        IDFacture = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        IDClient = new javax.swing.JLabel();
        Prenom1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Numcham = new javax.swing.JComboBox<>();
        dateDcham = new javax.swing.JComboBox<>();
        jPanel19 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        clt5 = new javax.swing.JComboBox<>();
        clt6 = new javax.swing.JComboBox<>();
        jPanel22 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        NumchamText = new javax.swing.JLabel();
        DateDchamtext = new javax.swing.JLabel();
        remplirNumchambre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        datefacture = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Numsalle = new javax.swing.JComboBox<>();
        DateDsalle = new javax.swing.JComboBox<>();
        jPanel24 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        NumSalleText = new javax.swing.JLabel();
        DateDSalletext = new javax.swing.JLabel();
        remplirNumsalle = new javax.swing.JButton();
        print = new javax.swing.JButton();
        reservationsalle = new javax.swing.JButton();
        remplir = new javax.swing.JButton();
        vider = new javax.swing.JButton();
        reservationchambre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 5, 8));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc-click\\Documents\\NetBeansProjects\\HotelLaGazellee\\Documents\\NetBeansProjects\\JavaApplication7\\src\\HotelPackage\\exitpng.png")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1325, 14, 24, 25);

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 236, 228));
        jLabel1.setText("Facture");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(21, 14, 280, 32);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 60));

        jPanel2.setBackground(new java.awt.Color(244, 240, 235));
        jPanel2.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(250, 249, 248));
        jPanel5.setLayout(null);

        Nom.setBackground(java.awt.Color.white);
        Nom.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        Nom.setOpaque(true);
        jPanel5.add(Nom);
        Nom.setBounds(140, 70, 170, 30);

        jPanel12.setBackground(new java.awt.Color(244, 240, 235));

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 5, 8));
        jLabel8.setText("ID Facture");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel12);
        jPanel12.setBounds(20, 10, 110, 30);

        jPanel16.setBackground(new java.awt.Color(244, 240, 235));

        jLabel19.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(2, 5, 8));
        jLabel19.setText(" Prénom");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel16);
        jPanel16.setBounds(330, 70, 110, 30);

        jPanel15.setBackground(new java.awt.Color(244, 240, 235));

        jLabel17.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(2, 5, 8));
        jLabel17.setText("Nom");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel15);
        jPanel15.setBounds(20, 70, 110, 30);

        IDFacture.setBackground(new java.awt.Color(250, 249, 248));
        IDFacture.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        IDFacture.setForeground(new java.awt.Color(2, 5, 8));
        IDFacture.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                IDFactureItemStateChanged(evt);
            }
        });
        IDFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFactureActionPerformed(evt);
            }
        });
        jPanel5.add(IDFacture);
        IDFacture.setBounds(160, 10, 211, 30);

        jPanel17.setBackground(new java.awt.Color(244, 240, 235));

        jLabel20.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(2, 5, 8));
        jLabel20.setText("IDClient");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel17);
        jPanel17.setBounds(400, 10, 110, 30);

        IDClient.setBackground(java.awt.Color.white);
        IDClient.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        IDClient.setOpaque(true);
        jPanel5.add(IDClient);
        IDClient.setBounds(520, 10, 170, 30);

        Prenom1.setBackground(java.awt.Color.white);
        Prenom1.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        Prenom1.setOpaque(true);
        jPanel5.add(Prenom1);
        Prenom1.setBounds(450, 70, 170, 30);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(42, 19, 730, 110);

        jPanel6.setBackground(new java.awt.Color(250, 249, 248));
        jPanel6.setLayout(null);

        jPanel13.setBackground(new java.awt.Color(244, 240, 235));

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 5, 8));
        jLabel10.setText("NumChambre");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(jPanel13);
        jPanel13.setBounds(20, 10, 160, 30);

        Numcham.setBackground(new java.awt.Color(250, 249, 248));
        Numcham.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        Numcham.setForeground(new java.awt.Color(2, 5, 8));
        Numcham.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NumchamItemStateChanged(evt);
            }
        });
        Numcham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumchamActionPerformed(evt);
            }
        });
        jPanel6.add(Numcham);
        Numcham.setBounds(200, 10, 211, 30);

        dateDcham.setBackground(new java.awt.Color(250, 249, 248));
        dateDcham.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        dateDcham.setForeground(new java.awt.Color(2, 5, 8));
        dateDcham.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dateDchamItemStateChanged(evt);
            }
        });
        dateDcham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDchamActionPerformed(evt);
            }
        });
        jPanel6.add(dateDcham);
        dateDcham.setBounds(200, 60, 211, 30);

        jPanel19.setBackground(new java.awt.Color(244, 240, 235));

        jLabel12.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(2, 5, 8));
        jLabel12.setText("Date début");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.add(jPanel19);
        jPanel19.setBounds(20, 60, 160, 30);

        jPanel7.setBackground(new java.awt.Color(250, 249, 248));
        jPanel7.setLayout(null);

        jPanel21.setBackground(new java.awt.Color(244, 240, 235));

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(2, 5, 8));
        jLabel14.setText("NumChambre");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.add(jPanel21);
        jPanel21.setBounds(20, 10, 160, 30);

        clt5.setBackground(new java.awt.Color(250, 249, 248));
        clt5.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        clt5.setForeground(new java.awt.Color(2, 5, 8));
        clt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clt5ActionPerformed(evt);
            }
        });
        jPanel7.add(clt5);
        clt5.setBounds(200, 10, 211, 30);

        clt6.setBackground(new java.awt.Color(250, 249, 248));
        clt6.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        clt6.setForeground(new java.awt.Color(2, 5, 8));
        clt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clt6ActionPerformed(evt);
            }
        });
        jPanel7.add(clt6);
        clt6.setBounds(200, 60, 211, 30);

        jPanel22.setBackground(new java.awt.Color(244, 240, 235));

        jLabel15.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 5, 8));
        jLabel15.setText("Date début");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.add(jPanel22);
        jPanel22.setBounds(20, 60, 160, 30);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(50, 140, 720, 110);

        NumchamText.setBackground(java.awt.Color.white);
        NumchamText.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        NumchamText.setOpaque(true);
        jPanel6.add(NumchamText);
        NumchamText.setBounds(450, 10, 170, 30);

        DateDchamtext.setBackground(java.awt.Color.white);
        DateDchamtext.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        DateDchamtext.setOpaque(true);
        jPanel6.add(DateDchamtext);
        DateDchamtext.setBounds(450, 60, 170, 30);

        remplirNumchambre.setBackground(new java.awt.Color(0, 0, 0));
        remplirNumchambre.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        remplirNumchambre.setForeground(new java.awt.Color(250, 249, 248));
        remplirNumchambre.setText("+");
        remplirNumchambre.setPreferredSize(new java.awt.Dimension(150, 52));
        remplirNumchambre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                remplirNumchambreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                remplirNumchambreFocusLost(evt);
            }
        });
        remplirNumchambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remplirNumchambreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                remplirNumchambreMousePressed(evt);
            }
        });
        remplirNumchambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remplirNumchambreActionPerformed(evt);
            }
        });
        jPanel6.add(remplirNumchambre);
        remplirNumchambre.setBounds(670, 80, 60, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(40, 170, 730, 110);

        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(840, 70, 490, 560);

        jLabel9.setBackground(new java.awt.Color(250, 249, 248));
        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 5, 8));
        jLabel9.setText("Date de facturation");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(830, 20, 189, 30);

        jPanel14.setBackground(new java.awt.Color(244, 240, 235));

        jLabel18.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(2, 5, 8));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel14);
        jPanel14.setBounds(600, 230, 200, 30);

        datefacture.setBackground(java.awt.Color.white);
        datefacture.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        datefacture.setOpaque(true);
        jPanel2.add(datefacture);
        datefacture.setBounds(1030, 20, 160, 30);

        jPanel3.setBackground(new java.awt.Color(250, 249, 248));

        jPanel23.setBackground(new java.awt.Color(244, 240, 235));

        jLabel16.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(2, 5, 8));
        jLabel16.setText("NumSalle");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Numsalle.setBackground(new java.awt.Color(250, 249, 248));
        Numsalle.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        Numsalle.setForeground(new java.awt.Color(2, 5, 8));
        Numsalle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NumsalleItemStateChanged(evt);
            }
        });
        Numsalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumsalleActionPerformed(evt);
            }
        });

        DateDsalle.setBackground(new java.awt.Color(250, 249, 248));
        DateDsalle.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        DateDsalle.setForeground(new java.awt.Color(2, 5, 8));
        DateDsalle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DateDsalleItemStateChanged(evt);
            }
        });
        DateDsalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateDsalleActionPerformed(evt);
            }
        });

        jPanel24.setBackground(new java.awt.Color(244, 240, 235));

        jLabel21.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(2, 5, 8));
        jLabel21.setText("Date début");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        NumSalleText.setBackground(java.awt.Color.white);
        NumSalleText.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        NumSalleText.setOpaque(true);

        DateDSalletext.setBackground(java.awt.Color.white);
        DateDSalletext.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        DateDSalletext.setOpaque(true);

        remplirNumsalle.setBackground(new java.awt.Color(0, 0, 0));
        remplirNumsalle.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        remplirNumsalle.setForeground(new java.awt.Color(250, 249, 248));
        remplirNumsalle.setText("+");
        remplirNumsalle.setPreferredSize(new java.awt.Dimension(150, 52));
        remplirNumsalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                remplirNumsalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                remplirNumsalleFocusLost(evt);
            }
        });
        remplirNumsalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remplirNumsalleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                remplirNumsalleMousePressed(evt);
            }
        });
        remplirNumsalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remplirNumsalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numsalle, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateDsalle, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(NumSalleText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(DateDSalletext, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(remplirNumsalle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numsalle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumSalleText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateDsalle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateDSalletext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(remplirNumsalle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(40, 330, 730, 110);

        print.setBackground(new java.awt.Color(0, 0, 0));
        print.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        print.setForeground(new java.awt.Color(250, 249, 248));
        print.setText("Print");
        print.setPreferredSize(new java.awt.Dimension(150, 52));
        print.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                printFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                printFocusLost(evt);
            }
        });
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                printMousePressed(evt);
            }
        });
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel2.add(print);
        print.setBounds(650, 590, 140, 43);

        reservationsalle.setBackground(new java.awt.Color(0, 0, 0));
        reservationsalle.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        reservationsalle.setForeground(new java.awt.Color(250, 249, 248));
        reservationsalle.setText("Reservation salles");
        reservationsalle.setPreferredSize(new java.awt.Dimension(150, 52));
        reservationsalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reservationsalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reservationsalleFocusLost(evt);
            }
        });
        reservationsalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationsalleMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reservationsalleMousePressed(evt);
            }
        });
        reservationsalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationsalleActionPerformed(evt);
            }
        });
        jPanel2.add(reservationsalle);
        reservationsalle.setBounds(40, 300, 240, 30);

        remplir.setBackground(new java.awt.Color(0, 0, 0));
        remplir.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        remplir.setForeground(new java.awt.Color(250, 249, 248));
        remplir.setText("Remplir");
        remplir.setPreferredSize(new java.awt.Dimension(150, 52));
        remplir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                remplirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                remplirFocusLost(evt);
            }
        });
        remplir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remplirMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                remplirMousePressed(evt);
            }
        });
        remplir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remplirActionPerformed(evt);
            }
        });
        jPanel2.add(remplir);
        remplir.setBounds(350, 590, 140, 43);

        vider.setBackground(new java.awt.Color(0, 0, 0));
        vider.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        vider.setForeground(new java.awt.Color(250, 249, 248));
        vider.setText("Vider");
        vider.setPreferredSize(new java.awt.Dimension(150, 52));
        vider.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                viderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                viderFocusLost(evt);
            }
        });
        vider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viderMousePressed(evt);
            }
        });
        vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderActionPerformed(evt);
            }
        });
        jPanel2.add(vider);
        vider.setBounds(500, 590, 140, 43);

        reservationchambre.setBackground(new java.awt.Color(0, 0, 0));
        reservationchambre.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        reservationchambre.setForeground(new java.awt.Color(250, 249, 248));
        reservationchambre.setText("Reservation chambres");
        reservationchambre.setPreferredSize(new java.awt.Dimension(150, 52));
        reservationchambre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reservationchambreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reservationchambreFocusLost(evt);
            }
        });
        reservationchambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationchambreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reservationchambreMousePressed(evt);
            }
        });
        reservationchambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationchambreActionPerformed(evt);
            }
        });
        jPanel2.add(reservationchambre);
        reservationchambre.setBounds(40, 140, 240, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1460, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed

        this.dispose();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void remplirNumsalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remplirNumsalleActionPerformed
 try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL="select prixTotal from reservationsalle where IDSalle='"+NumSalleText.getText().toString()+"' and DateD='"+DateDSalletext.getText().toString()+"' and IDClient='"+IDClient.getText().toString()+"'";
            ResultSet rs= st.executeQuery(SQL);
            while(rs.next()){
                //add data until finish
              prixsalle=rs.getDouble("prixTotal");
              prixtotalesalle=prixtotalesalle+prixsalle;
            }
            cnx.close();
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
        Text.append("\t "+NumSalleText.getText().toString()+"\t\t\t"+prixsalle+"\n\n");      
    }//GEN-LAST:event_remplirNumsalleActionPerformed

    private void remplirNumsalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remplirNumsalleMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirNumsalleMousePressed

    private void remplirNumsalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remplirNumsalleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirNumsalleMouseClicked

    private void remplirNumsalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remplirNumsalleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirNumsalleFocusLost

    private void remplirNumsalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remplirNumsalleFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirNumsalleFocusGained

    private void IDFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFactureActionPerformed
        
            
    }//GEN-LAST:event_IDFactureActionPerformed

    private void NumchamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumchamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumchamActionPerformed

    private void clt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clt5ActionPerformed

    private void clt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clt6ActionPerformed

    private void DateDsalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateDsalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateDsalleActionPerformed

    private void printFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_printFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_printFocusGained

    private void printFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_printFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_printFocusLost

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_printMouseClicked

    private void printMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_printMousePressed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
     try {
         Text.print();
     } catch (PrinterException ex) {
         Logger.getLogger(PrintFacture.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_printActionPerformed

    private void IDFactureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_IDFactureItemStateChanged
          if (evt.getStateChange() == evt.SELECTED) {
          Object item = evt.getItem();
          Numcham.removeAllItems();
          Numsalle.removeAllItems();
               try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            Connection cnx2 =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st2 =cnx2.createStatement();
            Connection cnx3 =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st3 =cnx3.createStatement();
             Connection cnx4 =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st4 =cnx3.createStatement();
            //requete
            String SQL="select IDClient,Date from facture where IDFacture= '"+item.toString()+"'";
            ResultSet rs= st.executeQuery(SQL);
            while(rs.next()){
                //add data until finish
              IDClient.setText(rs.getString("IDClient"));
              datefacture.setText(rs.getString("Date"));
            }
            cnx.close();
            String SQL2="select Nom,Prenom from clientt where Id_client='"+IDClient.getText().toString()+"'";
            ResultSet rs2= st2.executeQuery(SQL2);
            while(rs2.next()){
            Nom.setText(rs2.getString("Nom"));
            Prenom1.setText(rs2.getString("Prenom"));
            }
            cnx2.close();
             String SQL3="select distinct IDChambre from reservationchambre where IDClient='"+IDClient.getText().toString()+"'";
            ResultSet rs3= st3.executeQuery(SQL3);
            
            while(rs3.next()){
            Numcham.addItem(rs3.getString("IDChambre"));
            }
            String SQL4="select distinct IDSalle from reservationSalle where IDClient='"+IDClient.getText().toString()+"'";
            ResultSet rs4= st4.executeQuery(SQL4);
            
            while(rs4.next()){
            Numsalle.addItem(rs4.getString("IDSalle"));
            }
            cnx2.close();
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
               }
    }//GEN-LAST:event_IDFactureItemStateChanged

    private void NumsalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumsalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumsalleActionPerformed

    private void dateDchamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDchamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateDchamActionPerformed

    private void NumchamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NumchamItemStateChanged
        
        if (evt.getStateChange() == evt.SELECTED) {
          Object item = evt.getItem();
          dateDcham.removeAllItems();
         NumchamText.setText("");
         NumchamText.setText(item.toString());
         if(!(item.toString().isEmpty())){
        try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL="select distinct DateD from reservationchambre where IDClient='"+IDClient.getText().toString()+"' and IDChambre='"+item.toString()+"'";
            ResultSet rs= st.executeQuery(SQL);
            while(rs.next()){
                //add data until finish
              dateDcham.addItem(rs.getString("DateD"));
            }
            cnx.close();
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
        }}
    }//GEN-LAST:event_NumchamItemStateChanged

    private void dateDchamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dateDchamItemStateChanged
        if (evt.getStateChange() == evt.SELECTED) {
          Object item = evt.getItem();
         DateDchamtext.setText("");
         DateDchamtext.setText(item.toString());
        }
    }//GEN-LAST:event_dateDchamItemStateChanged

    private void NumsalleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NumsalleItemStateChanged
         if (evt.getStateChange() == evt.SELECTED) {
          Object item = evt.getItem();
          DateDsalle.removeAllItems();
         NumSalleText.setText("");
         NumSalleText.setText(item.toString());
         if(!(item.toString().isEmpty())){
        try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL="select distinct DateD from reservationsalle where IDClient='"+IDClient.getText().toString()+"' and IDSalle='"+item.toString()+"'";
            ResultSet rs= st.executeQuery(SQL);
            while(rs.next()){
                //add data until finish
              DateDsalle.addItem(rs.getString("DateD"));
            }
            cnx.close();
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
        }}
    }//GEN-LAST:event_NumsalleItemStateChanged

    private void DateDsalleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DateDsalleItemStateChanged
         if (evt.getStateChange() == evt.SELECTED) {
          Object item = evt.getItem();
         DateDSalletext.setText("");
         DateDSalletext.setText(item.toString());
        }
    }//GEN-LAST:event_DateDsalleItemStateChanged

    private void reservationsalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reservationsalleFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationsalleFocusGained

    private void reservationsalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reservationsalleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationsalleFocusLost

    private void reservationsalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationsalleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationsalleMouseClicked

    private void reservationsalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationsalleMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationsalleMousePressed

    private void reservationsalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationsalleActionPerformed
       Text.append("\t************************************************************\t\n\n"+"\t Résrvation des salles\t\tPrix \n"+"\t************************************************************\t\n\n");
    }//GEN-LAST:event_reservationsalleActionPerformed

    private void remplirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remplirFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirFocusGained

    private void remplirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remplirFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirFocusLost

    private void remplirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remplirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirMouseClicked

    private void remplirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remplirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirMousePressed

    private void remplirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remplirActionPerformed
       Text.append("\t************************************************************\t\n\n"+"\t Consommation des produits\t\tPrix \n"+"\t************************************************************\t\n\n");
        try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            Connection cnx2 =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st2 =cnx2.createStatement();
            //requete
            String SQL="select libelle,quantite,prixTotal from `produit`,`consommationproduits` where produit.IDproduit=consommationproduits.IDproduit and IDFacture='"+IDFacture.getSelectedItem().toString()+"'";
            ResultSet rs= st.executeQuery(SQL);
            
            while(rs.next()){
                //add data until finish
              String produit= rs.getString("libelle");
              int quantite= rs.getInt("quantite");
              prixproduit= rs.getDouble("prixTotal");
              prixproduittotal=prixproduittotal+prixproduit; 
              Text.append("\t"+produit+"\t           "+quantite+"\t\t"+prixproduit+"\t\t\n");
            }
            cnx.close();
            Text.append("\t************************************************************\t\n\n"+"\t Consommation des appels\t\tPrix \n"+"\t************************************************************\t\n\n");
            String SQL2="SELECT * FROM `consommationappels` WHERE `IDFacture`= '"+IDFacture.getSelectedItem().toString()+"'";
            ResultSet rs2= st2.executeQuery(SQL2);
            while(rs2.next()){
                //add data until finish
              String appel= rs2.getString("IDAppel");
              int duree= rs2.getInt("duree");
              prixpappel= rs2.getDouble("prixTotal");
              prixappeltotal=prixappeltotal+prixpappel; 
              Text.append("\t"+appel+"\t           "+duree+"\t\t"+prixpappel+"\t\t\n");
            }
            cnx2.close();
            Text.append("\t************************************************************\t\n\n");
            prixtotal= prixtotalechambre+prixtotalechambre+prixproduittotal+prixappeltotal;
            Text.append("\t Le prix Total des réservations des chambres = "+prixtotalechambre+" DA\t\n"+
                    "\t Le prix Total des réservations des salles = "+prixtotalechambre+" DA\t\n"+
                    "\t Le prix Total des consommation des produis = "+prixproduittotal+" DA\t\n"+
                    "\t Le prix Total des consommation des appels = "+prixappeltotal+" DA\t\n" +
                    "\t Le prix Total ="+prixtotal+"DA \t\n\n"+
            "\t*********************** MERCI POUR LA VISITE *********************\t\n\n");
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
        
    }//GEN-LAST:event_remplirActionPerformed

    private void remplirNumchambreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remplirNumchambreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirNumchambreFocusGained

    private void remplirNumchambreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remplirNumchambreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirNumchambreFocusLost

    private void remplirNumchambreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remplirNumchambreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirNumchambreMouseClicked

    private void remplirNumchambreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remplirNumchambreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_remplirNumchambreMousePressed

    private void remplirNumchambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remplirNumchambreActionPerformed
        
           try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL="select prixTotal from reservationchambre where IDChambre='"+NumchamText.getText().toString()+"' and DateD='"+DateDchamtext.getText().toString()+"' and IDClient='"+IDClient.getText().toString()+"'";
            ResultSet rs= st.executeQuery(SQL);
            while(rs.next()){
                //add data until finish
              prixchambre=rs.getDouble("prixTotal");
              prixtotalechambre=prixtotalechambre+prixchambre;
            }
            cnx.close();
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
        Text.append("\t "+NumchamText.getText().toString()+"\t\t\t"+prixchambre+"\n\n");
    }//GEN-LAST:event_remplirNumchambreActionPerformed

    private void viderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_viderFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_viderFocusGained

    private void viderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_viderFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_viderFocusLost

    private void viderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viderMouseClicked

    private void viderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viderMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viderMousePressed

    private void viderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderActionPerformed
        Text.removeAll();
    }//GEN-LAST:event_viderActionPerformed

    private void reservationchambreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reservationchambreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationchambreFocusGained

    private void reservationchambreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reservationchambreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationchambreFocusLost

    private void reservationchambreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationchambreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationchambreMouseClicked

    private void reservationchambreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationchambreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationchambreMousePressed

    private void reservationchambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationchambreActionPerformed
        Text.append("\t Résrvation des chambres\t\tPrix \n"+"\t************************************************************\t\n\n");
    }//GEN-LAST:event_reservationchambreActionPerformed
    public void updateIDFacture(){
    //remplir IdFacture
      try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL="select IDFacture from facture;";
            ResultSet rs= st.executeQuery(SQL);
            while(rs.next()){
                //add data until finish
              IDFacture.addItem(rs.getString("IDFacture"));
            }
            cnx.close();
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
    }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintFacture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateDSalletext;
    private javax.swing.JLabel DateDchamtext;
    private javax.swing.JComboBox<String> DateDsalle;
    private javax.swing.JLabel IDClient;
    private javax.swing.JComboBox<String> IDFacture;
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel NumSalleText;
    private javax.swing.JComboBox<String> Numcham;
    private javax.swing.JLabel NumchamText;
    private javax.swing.JComboBox<String> Numsalle;
    private javax.swing.JLabel Prenom1;
    private javax.swing.JTextArea Text;
    private javax.swing.JComboBox<String> clt5;
    private javax.swing.JComboBox<String> clt6;
    private javax.swing.JComboBox<String> dateDcham;
    private javax.swing.JLabel datefacture;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    private javax.swing.JButton remplir;
    private javax.swing.JButton remplirNumchambre;
    private javax.swing.JButton remplirNumsalle;
    private javax.swing.JButton reservationchambre;
    private javax.swing.JButton reservationsalle;
    private javax.swing.JButton vider;
    // End of variables declaration//GEN-END:variables
}
