/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelPackage;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author pc-click
 */
public class Salle extends javax.swing.JFrame {

    /**
     * Creates new form Salle
     */
    public Salle() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
        updatetable();
        jTable.getTableHeader().setFont(new Font ("Bell MT",Font.BOLD,14));
        jTable.getTableHeader().setOpaque(false);
        jTable.getTableHeader().setBackground(new Color(250,249,248));
        jTable.getTableHeader().setForeground(new Color(2,5,8));
        jTable.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Bsupprimer = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        BFiche = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        RechercheFiled = new javax.swing.JTextField();
        Bchercher = new javax.swing.JButton();
        BNouveau2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 5, 8));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 236, 228));
        jLabel1.setText("Salle");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(21, 14, 57, 32);

        jButton1.setBackground(new java.awt.Color(0, 0, 0,0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelPackage/exitpng.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1325, 14, 24, 25);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 60));

        jPanel2.setBackground(new java.awt.Color(250, 249, 248));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bsupprimer.setBackground(new java.awt.Color(250, 249, 248));
        Bsupprimer.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        Bsupprimer.setForeground(new java.awt.Color(2, 5, 8));
        Bsupprimer.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc-click\\Documents\\NetBeansProjects\\HotelLaGazellee\\Documents\\NetBeansProjects\\JavaApplication7\\src\\HotelPackage\\deleteclient.png")); // NOI18N
        Bsupprimer.setText(" Supprimer");
        Bsupprimer.setPreferredSize(new java.awt.Dimension(150, 52));
        Bsupprimer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BsupprimerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BsupprimerFocusLost(evt);
            }
        });
        Bsupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BsupprimerMousePressed(evt);
            }
        });
        Bsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsupprimerActionPerformed(evt);
            }
        });
        jPanel2.add(Bsupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 158, 43));

        refresh.setBackground(new java.awt.Color(250, 249, 248));
        refresh.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        refresh.setForeground(new java.awt.Color(2, 5, 8));
        refresh.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc-click\\Documents\\NetBeansProjects\\HotelLaGazellee\\Documents\\NetBeansProjects\\JavaApplication7\\src\\HotelPackage\\update.png")); // NOI18N
        refresh.setText("refresh");
        refresh.setPreferredSize(new java.awt.Dimension(150, 52));
        refresh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                refreshFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                refreshFocusLost(evt);
            }
        });
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                refreshMousePressed(evt);
            }
        });
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel2.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, 43));

        BFiche.setBackground(new java.awt.Color(250, 249, 248));
        BFiche.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        BFiche.setForeground(new java.awt.Color(2, 5, 8));
        BFiche.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc-click\\Documents\\NetBeansProjects\\HotelLaGazellee\\Documents\\NetBeansProjects\\JavaApplication7\\src\\HotelPackage\\stylo.png")); // NOI18N
        BFiche.setText("Modifier");
        BFiche.setPreferredSize(new java.awt.Dimension(150, 52));
        BFiche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BFicheFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BFicheFocusLost(evt);
            }
        });
        BFiche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BFicheMousePressed(evt);
            }
        });
        BFiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFicheActionPerformed(evt);
            }
        });
        jPanel2.add(BFiche, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 240, -1, 43));

        jTable.setBackground(new java.awt.Color(250, 249, 248));
        jTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable.setForeground(new java.awt.Color(2, 5, 8));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°Salle", "Prix", "Catégorie"
            }
        ));
        jTable.setFocusable(false);
        jTable.setGridColor(new java.awt.Color(2, 5, 8));
        jTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable.setRowHeight(25);
        jTable.setSelectionBackground(new java.awt.Color(2, 5, 8));
        jTable.setSelectionForeground(new java.awt.Color(250, 249, 248));
        jTable.setShowVerticalLines(false);
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 1330, 333));

        jComboBox.setBackground(new java.awt.Color(250, 249, 248));
        jComboBox.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jComboBox.setForeground(new java.awt.Color(2, 5, 8));
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NumSalle", "PrixSalle", "CategorieSalle", " ", " " }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 203, 36));

        jLabel18.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(2, 5, 8));
        jLabel18.setText("Recherche par");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 65, -1, -1));

        RechercheFiled.setBackground(new java.awt.Color(250, 250, 250));
        RechercheFiled.setFont(new java.awt.Font("Bell MT", 0, 20)); // NOI18N
        RechercheFiled.setForeground(new java.awt.Color(2, 5, 8));
        RechercheFiled.setSelectionColor(new java.awt.Color(2, 5, 8));
        jPanel2.add(RechercheFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 385, 38));

        Bchercher.setBackground(new java.awt.Color(250,249,248));
        Bchercher.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        Bchercher.setForeground(new java.awt.Color(2,5,8));
        Bchercher.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc-click\\Documents\\NetBeansProjects\\HotelLaGazellee\\Documents\\NetBeansProjects\\JavaApplication7\\src\\HotelPackage\\chercher.png")); // NOI18N
        Bchercher.setPreferredSize(new java.awt.Dimension(150, 52));
        Bchercher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BchercherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BchercherFocusLost(evt);
            }
        });
        Bchercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BchercherMousePressed(evt);
            }
        });
        Bchercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BchercherActionPerformed(evt);
            }
        });
        jPanel2.add(Bchercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, 52, 38));

        BNouveau2.setBackground(new java.awt.Color(250, 249, 248));
        BNouveau2.setFont(new java.awt.Font("Bell MT", 0, 22)); // NOI18N
        BNouveau2.setForeground(new java.awt.Color(2, 5, 8));
        BNouveau2.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc-click\\Documents\\NetBeansProjects\\HotelLaGazellee\\Documents\\NetBeansProjects\\JavaApplication7\\src\\HotelPackage\\plus.png")); // NOI18N
        BNouveau2.setText(" Nouveau");
        BNouveau2.setPreferredSize(new java.awt.Dimension(150, 52));
        BNouveau2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BNouveau2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BNouveau2FocusLost(evt);
            }
        });
        BNouveau2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BNouveau2MousePressed(evt);
            }
        });
        BNouveau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNouveau2ActionPerformed(evt);
            }
        });
        jPanel2.add(BNouveau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, -1, 43));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1460, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        new Accueil().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void BsupprimerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BsupprimerFocusGained

    }//GEN-LAST:event_BsupprimerFocusGained

    private void BsupprimerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BsupprimerFocusLost

    }//GEN-LAST:event_BsupprimerFocusLost

    private void BsupprimerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BsupprimerMousePressed
    int ligne =0;
        ligne=jTable.getSelectedRow();
        // recupere les elements
        String Numsalle =jTable.getValueAt(ligne,0).toString();
     
           try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL="delete from salle where NumSalle="+Numsalle+";";
            st.executeUpdate(SQL); 
           JOptionPane.showMessageDialog(this," Supprimer avec succès ","Info",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new Salle().setVisible(true);
           
           
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
           
    }//GEN-LAST:event_BsupprimerMousePressed

    private void BsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsupprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BsupprimerActionPerformed

    private void refreshFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_refreshFocusGained

    }//GEN-LAST:event_refreshFocusGained

    private void refreshFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_refreshFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshFocusLost

    private void refreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMousePressed
        
    }//GEN-LAST:event_refreshMousePressed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        new Salle().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_refreshActionPerformed

    private void BFicheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BFicheFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BFicheFocusGained

    private void BFicheFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BFicheFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_BFicheFocusLost

    private void BFicheMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BFicheMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BFicheMousePressed

    private void BFicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFicheActionPerformed
        new ModifierSalle().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BFicheActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed

    }//GEN-LAST:event_jComboBoxActionPerformed

    private void BchercherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BchercherFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BchercherFocusGained

    private void BchercherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BchercherFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_BchercherFocusLost

    private void BchercherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BchercherMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BchercherMousePressed

    private void BchercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BchercherActionPerformed

        String id= jComboBox.getSelectedItem().toString();
        String recherche= RechercheFiled.getText().toString();
        

        try{
            Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            System.err.println("1");
            //requete
            // String SQL="SELECT * FROM chambre WEHRE NumChambre  = "+ recherche+"";
            
            Statement st =cnx.createStatement();
          
            ResultSet rs= st.executeQuery("select * from salle where "+id+"='"+recherche+"';");
            if(!rs.isBeforeFirst()){
                JOptionPane.showMessageDialog(this," La salle n'existe pas !! ","Info",JOptionPane.INFORMATION_MESSAGE);
            }
            jTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e,"Erreur",JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_BchercherActionPerformed

    private void BNouveau2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BNouveau2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BNouveau2FocusGained

    private void BNouveau2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BNouveau2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_BNouveau2FocusLost

    private void BNouveau2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BNouveau2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BNouveau2MousePressed

    private void BNouveau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNouveau2ActionPerformed
        new FicheSalle().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BNouveau2ActionPerformed
    public void updatetable(){
        try{
           Class.forName("com.mysql.jdbc.Driver");
            System.err.println("connected");
            Connection cnx =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotellagazelle","root","");
            Statement st =cnx.createStatement();
            //requete
            String SQL="select * from salle";
            ResultSet rs= st.executeQuery(SQL);
            while(rs.next()){
                //add data until finish
                String NumSalle=String.valueOf(rs.getInt("NumSalle"));
                String prix=String.valueOf(rs.getInt("PrixSalle"));
                String categorie=String.valueOf(rs.getString("CategorieSalle"));
                String dispo=String.valueOf(rs.getInt("DisponibilteSalle"));
              
                
                //store in table
                
                String Table[]={NumSalle,prix,categorie,dispo};
                DefaultTableModel tbModel= (DefaultTableModel)jTable.getModel();
               
                tbModel.addRow(Table);
            }
            cnx.close();
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BFiche;
    private javax.swing.JButton BNouveau2;
    private javax.swing.JButton Bchercher;
    private javax.swing.JButton Bsupprimer;
    private javax.swing.JTextField RechercheFiled;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
